GOOS ?= $(go env GOOS)
GOARCH ?= $(go env GOARCH)
BUILDFLAGS ?=-ldflags "-X main.version=$(shell git describe --tags --always --dirty) -X main.buildDate=$(shell date +%Y-%m-%d)"

GO_OPTS?=CGO_ENABLED=$(CGO_ENABLED) GOOS=$(GOOS)
GO_TAGS?=
TEST_OPTS?=GOOS=$(GOOS) GOARCH=$(GOARCH)

# Configuration used by the integration tests. The defaults match the
# artifacts generated by setup_integration_tests.sh, so after running
# `sudo ./setup_integration_tests.sh` you can simply run the tests with
# `sudo -E PATH=$$PATH make -e integration-tests`. Every variable can be
# overridden through the environment, exactly like the GitHub Actions
# workflow does (see .github/workflows/build.yml).
SSH3_INTEGRATION_TESTS_KEY_DIR ?= /tmp/sshoq-integration-tests
CERT_PEM ?= $(SSH3_INTEGRATION_TESTS_KEY_DIR)/cert.pem
CERT_PRIV_KEY ?= $(SSH3_INTEGRATION_TESTS_KEY_DIR)/priv.key
ATTACKER_PRIVKEY ?= $(SSH3_INTEGRATION_TESTS_KEY_DIR)/attacker_id_rsa
TESTUSER_PRIVKEY ?= $(SSH3_INTEGRATION_TESTS_KEY_DIR)/testuser_id_rsa
TESTUSER_ED25519_PRIVKEY ?= $(SSH3_INTEGRATION_TESTS_KEY_DIR)/testuser_id_ed25519
TESTUSER_ECDSA_PRIVKEY ?= $(SSH3_INTEGRATION_TESTS_KEY_DIR)/testuser_id_ecdsa
TESTUSER_USERNAME ?= ssh3-testuser
ECDSATESTUSER_USERNAME ?= ssh3-ecdsa-testuser

default: build

clean:
	rm bin/*

build: sshoq sshoq-server

lint:
	go fmt ./...
	# FIXME: fix vet errors before turning this on
	# go vet ./...

test:
	$(TEST_OPTS) go test ./...
	$(TEST_OPTS) go run github.com/onsi/ginkgo/v2/ginkgo -r

integration-tests:
	CERT_PEM=$(CERT_PEM) \
		CERT_PRIV_KEY=$(CERT_PRIV_KEY) \
		ATTACKER_PRIVKEY=$(ATTACKER_PRIVKEY) \
		TESTUSER_PRIVKEY=$(TESTUSER_PRIVKEY) \
		TESTUSER_ED25519_PRIVKEY=$(TESTUSER_ED25519_PRIVKEY) \
		TESTUSER_ECDSA_PRIVKEY=$(TESTUSER_ECDSA_PRIVKEY) \
		TESTUSER_USERNAME=$(TESTUSER_USERNAME) \
		ECDSATESTUSER_USERNAME=$(ECDSATESTUSER_USERNAME) \
		CC=$(CC) \
		CGO_ENABLED=1 \
		GOOS=$(GOOS) \
		SSH3_INTEGRATION_TESTS_WITH_SERVER_ENABLED=1 \
		go run -v github.com/onsi/ginkgo/v2/ginkgo ./integration_tests

# Generates all keys, certificates and system users needed by the
# integration tests. Run it as root (the script checks for it):
#   sudo make integration-tests-setup
integration-tests-setup:
	./setup_integration_tests.sh

install:
	$(GO_OPTS) go install $(BUILDFLAGS) ./cmd/sshoq
	$(GO_OPTS) go install $(BUILDFLAGS) ./cmd/sshoq-server
	echo You might want to copy sshoq-server into /usr/sbin/ if you are running it via systemd

sshoq: ./cmd/sshoq ./cmd/sshoq.go ./client/  message resources util internal auth cmd/plugin_endpoint
	$(GO_OPTS) go build -tags "$(GO_TAGS)" $(BUILD_FLAGS) -o bin/sshoq ./cmd/sshoq/

sshoq-server: ./cmd/sshoq-server ./cmd/sshoq-server.go message server_auth resources util internal auth cmd/plugin_endpoint 
	$(GO_OPTS) go build -tags "$(GO_TAGS)" $(BUILD_FLAGS) -o bin/sshoq-server ./cmd/sshoq-server/

