#!/usr/bin/env bash
#
# setup_integration_tests.sh
#
# Sets up all the prerequisites required to run the sshoq integration tests
# locally (integration_tests/), mirroring what the "Integration tests" part
# of .github/workflows/build.yml does on GitHub Actions.
#
# The script is idempotent: it can safely be re-run (keys and users that
# already exist are left untouched, authorized_identities files are
# regenerated from scratch).
#
# Requirements:
#   - Linux (the sshoq-server integration tests only build on Linux)
#   - root privileges (test users are created and /home/<user> is modified)
#   - Go
#   - openssh-client, openssl and a C compiler (gcc); these are installed
#     automatically through apt-get when missing
#
# Usage:
#   sudo ./setup_integration_tests.sh
#
# Afterwards, run the tests with:
#   sudo -E PATH=$PATH make -e integration-tests
#
# Configuration:
#   SSH3_INTEGRATION_TESTS_KEY_DIR   directory where the generated keys and
#                                    certificates are stored
#                                    (default: /tmp/sshoq-integration-tests)
#                                    The Makefile `integration-tests` target
#                                    uses the same default, so no extra
#                                    configuration is needed for a plain run.
set -euo pipefail

KEY_DIR="${SSH3_INTEGRATION_TESTS_KEY_DIR:-/tmp/sshoq-integration-tests}"

TESTUSER="ssh3-testuser"
TESTPASSWD="ssh3-testpasswd"
ECDSATESTUSER="ssh3-ecdsa-testuser"
ECDSATESTPASSWD="ssh3-testpasswd"
TESTUSERHOME="/home/${TESTUSER}"
ECDSATESTUSERHOME="/home/${ECDSATESTUSER}"

# Artifacts generated by this script. The Makefile `integration-tests` target
# points at the same paths by default.
CERT_PEM="${KEY_DIR}/cert.pem"
CERT_PRIV_KEY="${KEY_DIR}/priv.key"
TESTUSER_PRIVKEY="${KEY_DIR}/testuser_id_rsa"
TESTUSER_ED25519_PRIVKEY="${KEY_DIR}/testuser_id_ed25519"
TESTUSER_ECDSA_PRIVKEY="${KEY_DIR}/testuser_id_ecdsa"
ATTACKER_PRIVKEY="${KEY_DIR}/attacker_id_rsa"

usage() {
    cat <<EOF
Usage: sudo $0

Sets up the prerequisites to run the sshoq integration tests locally:
  - generates the server self-signed certificate and the test SSH keys
  - creates the ssh3-testuser and ssh3-ecdsa-testuser system users
  - populates their ~/.ssh3/authorized_identities files

Afterwards, run the tests with:
  sudo -E PATH=\$PATH make -e integration-tests

Environment:
  SSH3_INTEGRATION_TESTS_KEY_DIR   directory for generated keys and
                                   certificates (default: /tmp/sshoq-integration-tests)
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

if [[ "$(uname -s)" != "Linux" ]]; then
    echo "error: the integration tests involving the sshoq server can only run on Linux" >&2
    exit 1
fi

if [[ $EUID -ne 0 ]]; then
    echo "error: this script must be run as root (it creates test users and writes into /home)" >&2
    echo "usage: sudo $0" >&2
    exit 1
fi

# Install missing dependencies (openssh-client, openssl and a C compiler).
# The sshoq server is compiled with CGO_ENABLED=1, hence gcc is required.
missing=()
command -v ssh-keygen >/dev/null 2>&1 || missing+=(openssh-client)
command -v openssl >/dev/null 2>&1 || missing+=(openssl)
command -v gcc >/dev/null 2>&1 || missing+=(build-essential)
if ((${#missing[@]})); then
    echo "==> Installing missing dependencies: ${missing[*]}"
    apt-get -y update
    apt-get -y install "${missing[@]}"
fi

if ! command -v go >/dev/null 2>&1; then
    echo "error: Go is required to run the integration tests (see https://go.dev/dl/)" >&2
    exit 1
fi

echo "==> Generating keys and certificates in ${KEY_DIR}"
mkdir -p "${KEY_DIR}"

# Server self-signed certificate (same command as generate_openssl_selfsigned_certificate.sh)
if [[ ! -f "${CERT_PEM}" || ! -f "${CERT_PRIV_KEY}" ]]; then
    pushd "${KEY_DIR}" >/dev/null
    openssl req -x509 -sha256 -nodes -newkey rsa:4096 -keyout priv.key -days 3660 \
        -out cert.pem -subj "/C=XX/O=Default Company/OU=XX/CN=selfsigned.ssh3" \
        -addext "subjectAltName = DNS:selfsigned.ssh3,DNS:*"
    popd >/dev/null
    echo "    wrote ${CERT_PEM} and ${CERT_PRIV_KEY}"
fi

# Test SSH keys (only generated when missing, so the script can be re-run)
[[ -f "${TESTUSER_PRIVKEY}" ]] || ssh-keygen -b 4096 -t rsa -f "${TESTUSER_PRIVKEY}" -q -N ""
[[ -f "${TESTUSER_ED25519_PRIVKEY}" ]] || ssh-keygen -t ed25519 -f "${TESTUSER_ED25519_PRIVKEY}" -q -N ""
[[ -f "${TESTUSER_ECDSA_PRIVKEY}" ]] || ssh-keygen -t ecdsa -f "${TESTUSER_ECDSA_PRIVKEY}" -q -N ""
# Attacker key: used to check that non-authorized identities are rejected
[[ -f "${ATTACKER_PRIVKEY}" ]] || ssh-keygen -b 4096 -t rsa -f "${ATTACKER_PRIVKEY}" -q -N ""

echo "==> Setting up test users"
if ! id "${TESTUSER}" >/dev/null 2>&1; then
    useradd -m -d "${TESTUSERHOME}" -s /bin/bash "${TESTUSER}"
    echo "    created user ${TESTUSER}"
else
    echo "    user ${TESTUSER} already exists"
fi
echo "${TESTUSER}:${TESTPASSWD}" | chpasswd

if ! id "${ECDSATESTUSER}" >/dev/null 2>&1; then
    useradd -m -d "${ECDSATESTUSERHOME}" -s /bin/bash "${ECDSATESTUSER}"
    echo "    created user ${ECDSATESTUSER}"
else
    echo "    user ${ECDSATESTUSER} already exists"
fi
echo "${ECDSATESTUSER}:${ECDSATESTPASSWD}" | chpasswd

echo "==> Creating .ssh and .ssh3 directories"
su "${TESTUSER}" -c "mkdir -p ${TESTUSERHOME}/.ssh ${TESTUSERHOME}/.ssh3"
su "${ECDSATESTUSER}" -c "mkdir -p ${ECDSATESTUSERHOME}/.ssh ${ECDSATESTUSERHOME}/.ssh3"

# Ensure there are no existing .profile or similar files for the testuser:
# the test suite writes its own .profile to check login-mode shell startup.
rm -f "${TESTUSERHOME}/.profile" "${TESTUSERHOME}/.bash_profile" "${TESTUSERHOME}/.bash_login"

echo "==> Populating authorized_identities"
# Truncate the file first so the script can safely be re-run
echo "# $(cat "${ATTACKER_PRIVKEY}.pub")" | tee "${TESTUSERHOME}/.ssh3/authorized_identities" >/dev/null
cat "${TESTUSER_PRIVKEY}.pub" "${TESTUSER_ED25519_PRIVKEY}.pub" | tee -a "${TESTUSERHOME}/.ssh3/authorized_identities" >/dev/null
# The ecdsa key is added to the ecdsa test user, used for retrocompatibility
# integration tests with server version 0.1.5 (ecdsa is not supported there)
cat "${TESTUSER_ECDSA_PRIVKEY}.pub" | tee -a "${ECDSATESTUSERHOME}/.ssh3/authorized_identities" >/dev/null

chown -R "${TESTUSER}:${TESTUSER}" "${TESTUSERHOME}/.ssh" "${TESTUSERHOME}/.ssh3"
chown -R "${ECDSATESTUSER}:${ECDSATESTUSER}" "${ECDSATESTUSERHOME}/.ssh" "${ECDSATESTUSERHOME}/.ssh3"

echo "==> ${TESTUSER}'s authorized_identities:"
cat "${TESTUSERHOME}/.ssh3/authorized_identities"

cat <<EOF

Integration test environment is ready.

Run the integration tests with:
    sudo -E PATH=\$PATH make -e integration-tests

The tests will use the keys and certificates generated in:
    ${KEY_DIR}
(override this directory with SSH3_INTEGRATION_TESTS_KEY_DIR)

Notes:
  - the tests must be run with root privileges and on Linux: the suite writes
    into ${TESTUSERHOME} and the sshoq-server only builds on Linux
  - the suite also installs old sshoq-server versions (v0.1.8, v0.1.10) from
    the network for retrocompatibility tests, so an internet connection is needed
EOF
